### PR TITLE
Feature/draggable

### PR DESCRIPTION
**Pull request by dangdennis**
Hi Kent, 

This is a long shot for a call for help, since you're quite the busy guy. But I took the mantle of trying to get the drag and drop to work. I found this scenario to be a fun and strange problem:

- Using Firebase to set the item order mixed
- Updating order state upon drag and drop and pushing it back to the server

Issue: After much attempt, I'm stuck on the part on how we're supposed set the order because we can't get that order just yet.

I'm adding a `handleDragItem` method to the FirebaseData class. That method is then passed as a prop into `DragDropContext`:  shown as `onDragEnd=(x) => handleDragItem(x,y)` which is a required prop for the DND library. The library is supposed to return to us the new index upon drop success.  With that new index, we set the order. However, it's unable to do so since the new index is unable to return a new value because the order state can't change due to firebase. I'm currently manually setting order to see if it works. 

I hope that's clear enough! Maybe I'd have this figured out on my own soon.

P.S. Thanks and sorry for using your API key. I wanted to skip the initial set-up haha.

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Thanks for working on this! I'm afraid that I haven't taken the time to make this project very contributor friendly (with my own eslint/prettier setup and gitignore). Maybe I'll find time to do that later.

For example, here's my normal prettier config:

```javascript
module.exports = {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: false,
  jsxBracketSameLine: false,
}
```

Also, I don't like committing lock files in my open source projects because they make working with contributors really challenging.

Right now your `src/index.js` has some merge conflicts left over somehow.

If you could clean up a few things there, then I'll give this another look. Thanks so much for trying!

**Review by kentcdodds — COMMENTED** [review]
Cool! Looking better! So you mentioned something about updating the order in firebase being a problem? Did you see [this function](https://github.com/dangdennis/repeat-todo-v2/blob/5a577ade0fa5f2942be8f3e5449d6095d0f36be1/src/index.js#L373)? Maybe that will help?

It's a bit of a pain to have to maintain the order manually, but it's the best I could come up with 🤷‍♂️

**Comment by dangdennis** [comment]
That prettier config was the cure. Hah. 

Yes, so the reorder function is near or at the crux of the problem hahaha. 

When you use the DragDropContext, it's supposed to passes the results of the drag and drop (source vs. destination) into our handleDragItem method. Unless I'm misunderstanding, it would give you the new index, but `results.destination.id` always equals `null`. That new`destination.id` would be what we'd use to set the new order through i.e. `reorderItems(item, itemsToMove, results.destination.id)`

Guess it comes down to whether results.destination.id comes from us (firebase) or the library 😢

**Comment by kentcdodds** [comment]
Interesting... So with firebase a collection is an object where the key is the id. So it doesn't have an id on the item (at least, I don't think so...)

**Comment by dangdennis** [comment]
Yeaup, that's it. It's all just objects. 

From the docs: 
> Persisting a reorder
If you need to persist a reorder to a remote data store - update the list synchronously on the client and fire off a request in the background to persist the change. If the remote save fails it is up to you how to communicate that to the user and update, or not update, the list.

What would you modify to maintain order state locally in this case?

Ahh, firebase. I'm gonna solve this since I'm considering Firebase for whatever side projects upcoming.

**Comment by kentcdodds** [comment]
Well, we just need to synchronously update the `order` property of all the items and hope that the firebase update finishes successfully (which it probably will).

**Pull request closed without merging**
