### PR TITLE
Custom confirms and prompts

### PR DESCRIPTION
**Pull request by askeroff**
Not sure if you needed this, but changed default browser prompts and confirms to customs ones with alertify.js library. I think, default ones are considered bad practice.

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Thanks for working on this! I'm not certain that I want it, but I can't review this very well. Could you do this again without adding all the semicolons?

**Comment by kentcdodds** [comment]
I looked at the preview and like the way it looks! Just want to know what it does to the code 😅

**Comment by askeroff** [comment]
Oh, it's probably the prettier working with semicolons. Should I open new PR for this?

**Comment by askeroff** [comment]
About what it does to the code, do you mean the library? I don't know about it's inner workings, but on the website it says 

> Currently, the entire library, with JavaScript and CSS is ~2.29 kB (gzipped), and getting smaller all the time. That's quite impressive considering it's only a single HTTP request, and no external dependencies at all being required.

**Pull request closed without merging**
